version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/local/src/ads-api
    ports:
      - 8000:8000
    depends_on:
      - db
      - store

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  store:
    image: redis:6-alpine
    ports:
      - 6380:6379

volumes:
  postgres_data:
